### ISSUE TITLE
reshared items do not contain a link to the item

### ISSUE THREAD

**Issue by propertunist** [ColdTrick/thewire_tools#18]
i am testing this master branch in elgg 1.11.2 and re-sharing bookmarks and videolist videos to the river. the river items are appearing but there are no links/videos attached to them. the river items do include the wire text that has been added via the popup when re-sharing, but that is all the info that is in them.

**Comment by propertunist** [comment]
this has been fixed in the latest version released to the community. an improvement over the basic text link that is available in the shared river item would be to also include some content and a way of showing how many times the item has been shared, as is the standard for other well known social nets.

**Comment by jdalsem** [comment]
> an improvement over the basic text link that is available in the shared river item would be to also include some content and

added this as a Feature Request to this plugin (#20)



> a way of showing how many times the item has been shared

this is already possible. On the original item you can she the reshare count
