### ISSUE TITLE
is_trusted flag is missing from thewire widget's 'more' link

### ISSUE THREAD

**Issue by propertunist** [ColdTrick/thewire_tools#21]
for seo purposes it is best to ensure that 'is_trusted' is set for internal links. the 'more' link at the bottom of the 'thewire' widget is missing this flag in the wiretools version of it.

**Comment by jdalsem** [comment]
feel free to submit a PR for these kinds of changes

**Comment by propertunist** [comment]
i have been having problems with github for a while, so the best i can do it report issues presently.. it's a long story!
