### ISSUE TITLE
profile status box should not show replies that are posted to the wire

### ISSUE THREAD

**Issue by propertunist** [ColdTrick/thewire_tools#22]
presently, if users reply to wire posts, then the status box on their profile that shows their most recent wire post will show the reply message. this is not such great behavior, since replies often contain text which cannot be understood without reading the full thread / context. it would be better to only show original wire posts in the status box on the profiles and not replies.

**Comment by jdalsem** [comment]
I disagree. Replies can also be valuable. There is no way to decide this, so we are leaving this as is.

**Comment by propertunist** [comment]
if i view someone's profile on every one of the successful social platforms, there will be a tagline of some kind to tell you quickly, something about the user. given the priority that has been assigned to the status box on the profiles by profile manager, i thought that this status box is the equivalent for elgg - which makes sense, since wire status messages can also be seen to be something of a tagline - but only if the original wire post is displayed. reply text can be totally random to a new user and cannot be understood, giving the profile a messy and incoherent appearance.

**Comment by jdalsem** [comment]
you are right that the 'status' box could be something like a tag line, but that is something else than the latest wire post. Personally, we most of the time drop this info on profile pages as wire posts do not make much sense here. We also like to keep it in line with Elgg default behaviour. Maybe you could start the discussion there.
