### ISSUE TITLE
browser dropdown renders for the wire/add input field on activity page

### ISSUE THREAD

**Issue by propertunist** [ColdTrick/thewire_tools#26]
as discussed in italy, i am seeing a dropdown being added by firefox (latest linux version) and chromium (windows 10) when a username beginning with a @ symbol is typed into the wire/add form on the activity page and the autocomplete dropdown is rendered. the browser's dropdown appears on top of the javascript one and so the JS one is hard to use. the content of the dropdown being added by the browser is slightly odd, in that it contains apparently technical entries, such as:

```
https://www.ureka.org/thewire/autocomplete?q=%40t&page_owner_guid=2 
```

and

```
undefined
```

'autocomplete' is set to 'off' for the field input and my chromium browser has no addons installed, so i know the problem is not coming from addons.

**Comment by jdalsem** [comment]
You also are using the mentions plugin right? Do you have the issue if that plugin is disabled? What version of wire_tools are you using?

**Comment by propertunist** [comment]
i am using 4.0.1 of wire tools with 1.12.4 of elgg currently. i am using mentions, yes. i just disabled mentions and found that the auto lookup box for usernames no longer functions. for some reason i though that the auto lookup dropdown was added by wiretools within the wire add form's input.. but obviously not. with mentions disabled, the browser's own dropdown still does render and contains the same text as i posted in my original comment here.
the browser dropdown only appears when i type a @ character and then some text.

**Comment by propertunist** [comment]
fyi, just upgraded to 1.12.9 and still see the same behavior. i'll carry on upgrading my code to 2.2 level and see what occurs.

**Comment by jdalsem** [comment]
i tried to reproduce this in my browser but, even if i try really hard, no browser autocomplete is happening on the input field on the wire form. Are you sure it is not an issue where both thewire tools AND the mentions plugin both try to show the autocomplete dropdown?

**Comment by jdalsem** [comment]
i noticed there is probably still a conflict between the mention feature of this plugin and that of the mentions plugin. We only fixed this in the elgg_1.8 branch of this plugin https://github.com/ColdTrick/thewire_tools/commit/fb6a4b1064fc67ebff4a04d057779218d357e277, so it still needs to find its way to the master branch

**Comment by propertunist** [comment]
i don't presently have any more information on this to help diagnose the source of the issue. if you let me know when the 1.8 fix is added to the 1.12 version i will re-test and let you know the outcome.

**Comment by propertunist** [comment]
so i have just put a couple of days into upgrading the elgg mentions plugin to make it compatible with elgg 2.1.2 and extended_tinymce. most of the aspects of it are now working correctly. i realised that i couldn't apply the mentions plugin to wire post input fields because the plaintext part of the mentions plugin didn't work well with those fields. i attempted to convert the wire input fields to use tinymce, but that also didn't work for an unknown reason..
so.. then i decided to look at fixing thewire_tools' autocomplete feature instead and not use the mentions plugin for wire posts...
so that brought me back to this open issue here.
i looked through the jquery code in thewire_tools/autocomplete.js and i don't really understand the mechanisms involved in the code - in terms of how each function is triggered. 
in any case, i found that what is being returned from the username autocomplete lookup is this:
```
function .proxy/f()
```
rather than any useful data.
it is possible that i just don't understand how the code is intended to function, but for the moment it looks to me like there is a bug with the lookup process.

**Comment by propertunist** [comment]
so i now see that autocomplete does add links to wire posts for usernames, but isn't bringing up a live menu of usernames when a @ symbol is typed.

**Comment by jdalsem** [comment]
mention feature currently rely on the ckeditor mentions feature; there is no longer any autocomplete feature part of this plugin
