### ISSUE TITLE
PHP7 compatibility - router needs new logic for array

### ISSUE THREAD

**Issue by propertunist** [ColdTrick/thewire_tools#27]
i have upgraded my server to PHP7 and am going through fixing the few issues that have been introduced. there are several places in plugins where the router hook receives a boolean return value and passes it to elgg_extract, which expects an array. this now produces a fatal error - so something like this is a workaround:

```
        // possible fix for PHP7
        if (!is_array($return))
        {
            $return = array($return);
        }
```

this effects several of your plugins, including blog_tools & thewire_tools.

**Comment by jeabakker** [comment]
this was fixed in Elgg core https://github.com/Elgg/Elgg/pull/10241
