### ISSUE TITLE
Text submitted in Friend's Wire does not show up.

### ISSUE THREAD

**Issue by daniyaree** [ColdTrick/thewire_tools#33]
A and B are friends, B can see Wire Form on A's profile, can submit text there. It shows success message but the text is not showed in the Wire of A.
Either disable visibilty of Wire form, when not own Wire
Or display submitted text.

**Comment by jeabakker** [comment]
This is an issue of Elgg core, moved the issue there

**Comment by jeabakker** [comment]
see https://github.com/Elgg/Elgg/issues/12285
