### ISSUE TITLE
Elgg3: drop search page

### ISSUE THREAD

**Issue by jdalsem** [ColdTrick/thewire_tools#35]
just use regular elgg search...

introduce a filter for mentions

**Comment by daniyaree** [comment]
Ability to search within an User's wire would be really useful. For example, atop an User's wire a search input box that allows to search word from that User's posts only, if possible, on a time basis eg. Jan 17 to Jan 18

**Comment by jdalsem** [comment]
search and mentions is no longer part of this plugin but is handled in core thewire plugin
