### ISSUE TITLE
Help with a small mod please

### ISSUE THREAD

**Issue by joey2354** [ColdTrick/thewire_tools#36]
hi there, i'm no coder sorry but i'm learning atm, i'm just wanting the share button popup box to have the source url in please.

https://i.imgur.com/kSg83Da.png 

thank you

**Comment by joey2354** [comment]
just to add i see the link when i share from a group post, but not anywhere else 

https://i.imgur.com/ATQCxHl.png

it just needs moving into the text field.


I can pay for this mod if need no problem :) 
thank you again

**Comment by jdalsem** [comment]
You could add the following to https://github.com/ColdTrick/thewire_tools/blob/master/views/default/forms/thewire/add.php#L50

```
$post_value .= ' ' . $reshare->getURL();
```

**Comment by joey2354** [comment]
thank you buddy that's worked :)
