### ISSUE TITLE
Testing with Elgg 3x

### ISSUE THREAD

**Issue by daniyaree** [ColdTrick/thewire_tools#38]
trying to test the latest available Wire Tools plugin from community repo with Elgg 3x (latest RC2). It installs the plugin in fine and smooth in the admin panel/admin pages. But the actual site shows "Fatal Error" and nothing else (php7x). Uninstalling brings back normalcy.
The downloadable zip version at github seems to lack start.php

**Comment by jeabakker** [comment]
You should use the 8.0+ releases. You can find them here https://github.com/ColdTrick/thewire_tools/releases
Community update will come soon

PS: `start.php` is no longer required in Elgg 3.0
