### ISSUE TITLE
removed function is used

### ISSUE THREAD

**Issue by jeabakker** [ColdTrick/thewire_tools#40]
**Elgg version**
3.3

**Plugin version**
master

**Plugin source**
- Git clone (did you run `composer install`?)

**Describe the bug**
I am using thewire_tool on my website. While I updated my plugins from Elgg2 to Elgg3, I found that on line 59 of thewire_tools/views/default/resources/thewire/autocomplete.php it still uses the removed function $tags_id = elgg_get_metastring_id('tags');

Cheers!

see: https://elgg.org/comment/view/3081443/3038917

**Comment by jdalsem** [comment]
This is an issue because the autocomplete features have never been updated for Elgg 3. This was already recorded in #30
