### ISSUE TITLE
TheWire for Groups feature is not working correctly

### ISSUE THREAD

**Issue by latra** [ColdTrick/thewire_tools#43]
**Elgg version**
3.3

**Plugin version**
9.1 & 9.1.1

**Plugin source**
- Elgg community page download (9.1)
- Github releases download (9.1.1)

**Describe the bug**
When I do a new post in the wire inside a group activity ({url}/activity/group/[group id]), the post is not publishing inside the group, instead it is publishing (and reporting) to all users in the global wire.
**To Reproduce**
1. Go to your group
2. Go to publish a new post inside the group
3. Publish something

**Expected behavior**
The post will be only available and notified to members of the group.

**Screenshots**
Non-applicable. If needed, I can do a video.

**Additional context**
We are also working with other plugins like The Wire Pro and Vision Theme.

**Comment by latra** [comment]
![image](https://user-images.githubusercontent.com/17687435/128488654-e3afb4ac-781d-4de4-84a2-061b5ff2e6f2.png)
We configure The Wire tools plugin in that way

**Comment by jeabakker** [comment]
On the group activity page I have this:
![afbeelding](https://user-images.githubusercontent.com/881958/128490360-ca376495-55f4-4bc1-a799-8e363d3f72f6.png)

If I check the Wire all page I get:
![afbeelding](https://user-images.githubusercontent.com/881958/128490453-0c7c33b2-7fad-484a-aa40-0390f2f6df57.png)

You can see that the Wire posts are created in the group.

Depending on the access you select in the first screenshot it can be visible to only group members or all logged in user or public.

Are you sure the Wire posts aren't created in the group? As I can't reproduce that issue.

**Comment by latra** [comment]
Hmmm, yes, I'm pretty sure. I attach to you a video doing the process of post a new message and how it's not working correctly.
Maybe can we have any kind of incompatibility with The WIre Pro o Vision theme?

https://user-images.githubusercontent.com/17687435/128492096-da6c5f6c-ee06-44fe-8773-38f77ac3e405.mp4

**Comment by jeabakker** [comment]
The video won't play :(

If there are other plugins active which also do thing with the wire, that could be an issue. Have you tried with all plugins disabled except:
- groups
- thewire
- thewire_tools
- activity

**Comment by latra** [comment]
I tried to disable all plugins but it is still without working.
I'm thinking that your screenshot has a field to set where you want to post the message (the "post-on-site" collapsible), but we don't. I'll keep looking at what is happening here.

Thanks for your help.

**Comment by latra** [comment]
Ok, I don't know why but just started to work. Maybe some kind of cache was doing something weird.
